mappings:
  OrderConverter: Sunnysideup\Ecommerce\Api\OrderConverter
  EcommerceRestfulServer: Sunnysideup\Ecommerce\Api\EcommerceRestfulServer
  EcommerceCountryVisitorCountryProvider: Sunnysideup\Ecommerce\Api\EcommerceCountryVisitorCountryProvider
  ShoppingCart: Sunnysideup\Ecommerce\Api\ShoppingCart
  ProductCollection: Sunnysideup\Ecommerce\Api\ProductCollection
  OrderToArray: Sunnysideup\Ecommerce\Api\Converters\OrderToArray
  EcommerceCodeFilter: Sunnysideup\Ecommerce\Dev\EcommerceCodeFilter
  OrderInvoiceEmail: Sunnysideup\Ecommerce\Email\OrderInvoiceEmail
  OrderErrorEmail: Sunnysideup\Ecommerce\Email\OrderErrorEmail
  EcommerceDummyMailer: Sunnysideup\Ecommerce\Email\EcommerceDummyMailer
  OrderStatusEmail: Sunnysideup\Ecommerce\Email\OrderStatusEmail
  OrderReceiptEmail: Sunnysideup\Ecommerce\Email\OrderReceiptEmail
  OrderEmail: Sunnysideup\Ecommerce\Email\OrderEmail
  ProductImage: Sunnysideup\Ecommerce\Filesystem\ProductImage
  EcommercePaymentSupportedMethodsProviderInterface: Sunnysideup\Ecommerce\Interfaces\EcommercePaymentSupportedMethodsProviderInterface
  OrderStepInterface: Sunnysideup\Ecommerce\Interfaces\OrderStepInterface
  EcommerceGEOipProvider: Sunnysideup\Ecommerce\Interfaces\EcommerceGEOipProvider
  EditableEcommerceObject: Sunnysideup\Ecommerce\Interfaces\EditableEcommerceObject
  BuyableModel: Sunnysideup\Ecommerce\Interfaces\BuyableModel
  EcommerceConfigDefinitions: Sunnysideup\Ecommerce\Config\EcommerceConfigDefinitions
  EcommerceConfig: Sunnysideup\Ecommerce\Config\EcommerceConfig
  EcommerceConfigAjaxDefinitions: Sunnysideup\Ecommerce\Config\EcommerceConfigAjaxDefinitions
  EcommerceConfigAjax: Sunnysideup\Ecommerce\Config\EcommerceConfigAjax
  OrderModifierFormController: Sunnysideup\Ecommerce\Control\OrderModifierFormController
  OrderStatusLogFormController: Sunnysideup\Ecommerce\Control\OrderStatusLogFormController
  EcommerceResponse: Sunnysideup\Ecommerce\Control\EcommerceResponse
  EcommercePaymentController: Sunnysideup\Ecommerce\Control\EcommercePaymentController
  BuyableSelectFieldDataList: Sunnysideup\Ecommerce\Control\BuyableSelectFieldDataList
  EcommerceSiteTreeExtensionController: Sunnysideup\Ecommerce\Control\EcommerceSiteTreeExtensionController
  EcommerceTemplateTest: Sunnysideup\Ecommerce\Control\EcommerceTemplateTest
  OrderStepController: Sunnysideup\Ecommerce\Control\OrderStepController
  ShoppingCartController: Sunnysideup\Ecommerce\Control\ShoppingCartController
  CartResponse: Sunnysideup\Ecommerce\Control\CartResponse
  OrderEmailRecordReview: Sunnysideup\Ecommerce\Control\OrderEmailRecordReview
  ProductOrderItem: Sunnysideup\Ecommerce\Model\ProductOrderItem
  OrderAttribute: Sunnysideup\Ecommerce\Model\OrderAttribute
  OrderModifierDescriptor: Sunnysideup\Ecommerce\Model\OrderModifierDescriptor
  OrderItem: Sunnysideup\Ecommerce\Model\OrderItem
  OrderModifier: Sunnysideup\Ecommerce\Model\OrderModifier
  Order: Sunnysideup\Ecommerce\Model\Order
  OrderAttributeGroup: Sunnysideup\Ecommerce\Model\OrderAttributeGroup
  EcommerceDBConfig: Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig
  EcommerceRegionVisitorRegionProvider: Sunnysideup\Ecommerce\Model\Address\EcommerceRegionVisitorRegionProvider
  EcommerceRegion: Sunnysideup\Ecommerce\Model\Address\EcommerceRegion
  ShippingAddress: Sunnysideup\Ecommerce\Model\Address\ShippingAddress
  EcommerceCountry: Sunnysideup\Ecommerce\Model\Address\EcommerceCountry
  OrderAddress: Sunnysideup\Ecommerce\Model\Address\OrderAddress
  BillingAddress: Sunnysideup\Ecommerce\Model\Address\BillingAddress
  CheckoutPageStepDescription: Sunnysideup\Ecommerce\Model\Process\CheckoutPageStepDescription
  OrderStep: Sunnysideup\Ecommerce\Model\Process\OrderStep
  OrderEmailRecord: Sunnysideup\Ecommerce\Model\Process\OrderEmailRecord
  OrderProcessQueue: Sunnysideup\Ecommerce\Model\Process\OrderProcessQueue
  OrderStatusLog: Sunnysideup\Ecommerce\Model\Process\OrderStatusLog
  OrderFeedback: Sunnysideup\Ecommerce\Model\Process\OrderFeedback
  OrderStepCreated: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepCreated
  OrderStepSentReceipt: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepSentReceipt
  OrderStepSendAdminNotification: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepSendAdminNotification
  OrderStepSent: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepSent
  OrderStepSubmitted: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepSubmitted
  OrderStepArchived: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepArchived
  OrderStepConfirmed: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepConfirmed
  OrderStepPaid: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepPaid
  OrderStepSentInvoice: Sunnysideup\Ecommerce\Model\Process\OrderSteps\OrderStepSentInvoice
  OrderStatusLogCancel: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogCancel
  OrderStatusLogDispatchElectronicOrder: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogDispatchElectronicOrder
  OrderStatusLogDispatch: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogDispatch
  OrderStatusLogSubmitted: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogSubmitted
  OrderStatusLogArchived: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogArchived
  OrderStatusLogPaymentCheck: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogPaymentCheck
  OrderStatusLogDispatchPhysicalOrder: Sunnysideup\Ecommerce\Model\Process\OrderStatusLogs\OrderStatusLogDispatchPhysicalOrder
  EcommerceCurrency: Sunnysideup\Ecommerce\Model\Money\EcommerceCurrency
  EcommercePayment: Sunnysideup\Ecommerce\Model\Money\EcommercePayment
  EcommercePaymentTest: Sunnysideup\Ecommerce\Model\Money\PaymentTypes\EcommercePaymentTest
  EcommercePaymentTestPending: Sunnysideup\Ecommerce\Model\Money\PaymentTypes\EcommercePaymentTestPending
  EcommercePaymentTestSuccess: Sunnysideup\Ecommerce\Model\Money\PaymentTypes\EcommercePaymentTestSuccess
  EcommercePaymentTestFailure: Sunnysideup\Ecommerce\Model\Money\PaymentTypes\EcommercePaymentTestFailure
  SearchReplacement: Sunnysideup\Ecommerce\Model\Search\SearchReplacement
  SearchHistory: Sunnysideup\Ecommerce\Model\Search\SearchHistory
  BuyableFieldType: Sunnysideup\Ecommerce\Model\Fieldtypes\BuyableFieldType
  EcommerceRole: Sunnysideup\Ecommerce\Model\Extensions\EcommerceRole
  EcommerceSiteTreeExtension: Sunnysideup\Ecommerce\Model\Extensions\EcommerceSiteTreeExtension
  GridFieldAddNewButtonOriginalPage: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldAddNewButtonOriginalPage
  GridFieldPrintInvoiceButton: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldPrintInvoiceButton
  GridFieldExportSalesButton: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldExportSalesButton
  GridFieldEditButtonOriginalPage: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldEditButtonOriginalPage
  GridFieldPrintAllPackingSlipsButton: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldPrintAllPackingSlipsButton
  GridFieldPrintAllInvoicesButton: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldPrintAllInvoicesButton
  GridFieldPrintPackingSlipButton: Sunnysideup\Ecommerce\Forms\Gridfield\GridFieldPrintPackingSlipButton
  GridFieldBasicPageRelationConfig: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldBasicPageRelationConfig
  GridFieldEditOriginalPageConfigWithDelete: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldEditOriginalPageConfigWithDelete
  GridFieldEditOriginalPageConfigWithAddExisting: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldEditOriginalPageConfigWithAddExisting
  GridFieldConfigForOrderItems: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldConfigForOrderItems
  GridFieldBasicPageRelationConfigNoAddExisting: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldBasicPageRelationConfigNoAddExisting
  GridFieldEditOriginalPageConfig: Sunnysideup\Ecommerce\Forms\Gridfield\Configs\GridFieldEditOriginalPageConfig
  OrderFormAddress: Sunnysideup\Ecommerce\Forms\OrderFormAddress
  OrderFormPayment: Sunnysideup\Ecommerce\Forms\OrderFormPayment
  OrderFormCancel: Sunnysideup\Ecommerce\Forms\OrderFormCancel
  ProductSearchFormShort: Sunnysideup\Ecommerce\Forms\ProductSearchFormShort
  OrderForm: Sunnysideup\Ecommerce\Forms\OrderForm
  OrderFormFeedback: Sunnysideup\Ecommerce\Forms\OrderFormFeedback
  ShopAccountForm: Sunnysideup\Ecommerce\Forms\ShopAccountForm
  OrderStatusLogForm: Sunnysideup\Ecommerce\Forms\OrderStatusLogForm
  OrderModifierForm: Sunnysideup\Ecommerce\Forms\OrderModifierForm
  ProductSearchForm: Sunnysideup\Ecommerce\Forms\ProductSearchForm
  OptionalTreeDropdownField: Sunnysideup\Ecommerce\Forms\Fields\OptionalTreeDropdownField
  EcomQuantityField: Sunnysideup\Ecommerce\Forms\Fields\EcomQuantityField
  EcommerceSearchHistoryFormField: Sunnysideup\Ecommerce\Forms\Fields\EcommerceSearchHistoryFormField
  OrderStepField: Sunnysideup\Ecommerce\Forms\Fields\OrderStepField
  BuyableSelectField: Sunnysideup\Ecommerce\Forms\Fields\BuyableSelectField
  SelectOrderAddressField: Sunnysideup\Ecommerce\Forms\Fields\SelectOrderAddressField
  EcommerceClassNameOrTypeDropdownField: Sunnysideup\Ecommerce\Forms\Fields\EcommerceClassNameOrTypeDropdownField
  EcommerceCreditCardField: Sunnysideup\Ecommerce\Forms\Fields\EcommerceCreditCardField
  EcommerceCMSButtonField: Sunnysideup\Ecommerce\Forms\Fields\EcommerceCMSButtonField
  ExpiryDateField: Sunnysideup\Ecommerce\Forms\Fields\ExpiryDateField
  ProductProductImageUploadField: Sunnysideup\Ecommerce\Forms\Fields\ProductProductImageUploadField
  OrderFormAddressValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderFormAddressValidator
  ShopAccountFormValidator: Sunnysideup\Ecommerce\Forms\Validation\ShopAccountFormValidator
  OrderFormCancelValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderFormCancelValidator
  OrderFormValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderFormValidator
  OrderStatusLogFormValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderStatusLogFormValidator
  EcommercePaymentFormSetupAndValidation: Sunnysideup\Ecommerce\Forms\Validation\EcommercePaymentFormSetupAndValidation
  OrderFormPaymentValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderFormPaymentValidator
  ProductSearchFormValidator: Sunnysideup\Ecommerce\Forms\Validation\ProductSearchFormValidator
  ShopAccountFormPasswordValidator: Sunnysideup\Ecommerce\Forms\Validation\ShopAccountFormPasswordValidator
  OrderModifierFormValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderModifierFormValidator
  OrderFormFeedbackValidator: Sunnysideup\Ecommerce\Forms\Validation\OrderFormFeedbackValidator
  EcommerceMoney: Sunnysideup\Ecommerce\Money\EcommerceMoney
  EcommercePaymentSupportedMethodsProvider: Sunnysideup\Ecommerce\Money\EcommercePaymentSupportedMethodsProvider
  ExchangeRateProviderDummy: Sunnysideup\Ecommerce\Money\ExchangeRateProviderDummy
  ExchangeRateProvider: Sunnysideup\Ecommerce\Money\ExchangeRateProvider
  EcommercePaymentResult: Sunnysideup\Ecommerce\Money\Payment\EcommercePaymentResult
  EcommercePaymentProcessing: Sunnysideup\Ecommerce\Money\Payment\PaymentResults\EcommercePaymentProcessing
  EcommercePaymentSuccess: Sunnysideup\Ecommerce\Money\Payment\PaymentResults\EcommercePaymentSuccess
  EcommercePaymentFailure: Sunnysideup\Ecommerce\Money\Payment\PaymentResults\EcommercePaymentFailure
  EcommerceTaskCountryAndRegionDisallowAllCountries: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCountryAndRegionDisallowAllCountries
  EcommerceTaskAPIandMore: Sunnysideup\Ecommerce\Tasks\EcommerceTaskAPIandMore
  EcommerceTaskTemplateTest: Sunnysideup\Ecommerce\Tasks\EcommerceTaskTemplateTest
  EcommerceTaskSetOrderIDStartingNumber: Sunnysideup\Ecommerce\Tasks\EcommerceTaskSetOrderIDStartingNumber
  EcommerceTaskAddDefaultProducts: Sunnysideup\Ecommerce\Tasks\EcommerceTaskAddDefaultProducts
  EcommerceTaskCreateMemberGroups: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCreateMemberGroups
  EcommerceTaskBuildingModel: Sunnysideup\Ecommerce\Tasks\EcommerceTaskBuildingModel
  EcommerceTaskLinkProductWithImages: Sunnysideup\Ecommerce\Tasks\EcommerceTaskLinkProductWithImages
  EcommerceTaskOrdersWithoutOrderStep: Sunnysideup\Ecommerce\Tasks\EcommerceTaskOrdersWithoutOrderStep
  EcommerceTaskCartManipulationDebug: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCartManipulationDebug
  EcommerceTaskProductVariationsFixes: Sunnysideup\Ecommerce\Tasks\EcommerceTaskProductVariationsFixes
  EcommerceTaskArchiveAllOrdersWithItems: Sunnysideup\Ecommerce\Tasks\EcommerceTaskArchiveAllOrdersWithItems
  EcommerceTaskAddCustomersToCustomerGroups: Sunnysideup\Ecommerce\Tasks\EcommerceTaskAddCustomersToCustomerGroups
  EcommerceTaskBuildingExtending: Sunnysideup\Ecommerce\Tasks\EcommerceTaskBuildingExtending
  EcommerceTaskProductImageReset: Sunnysideup\Ecommerce\Tasks\EcommerceTaskProductImageReset
  EcommerceTaskArchiveAllSubmittedOrders: Sunnysideup\Ecommerce\Tasks\EcommerceTaskArchiveAllSubmittedOrders
  EcommerceTaskCartCleanup: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCartCleanup
  EcommerceTaskTryToFinaliseOrders: Sunnysideup\Ecommerce\Tasks\EcommerceTaskTryToFinaliseOrders
  EcommerceTaskCheckConfiguration: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCheckConfiguration
  EcommerceTaskDeleteAllOrders: Sunnysideup\Ecommerce\Tasks\EcommerceTaskDeleteAllOrders
  EcommerceTaskProcessOrderQueue: Sunnysideup\Ecommerce\Tasks\EcommerceTaskProcessOrderQueue
  EcommerceTaskLinkOrderAddressesAtBothEnds: Sunnysideup\Ecommerce\Tasks\EcommerceTaskLinkOrderAddressesAtBothEnds
  EcommerceTaskReviewSearches: Sunnysideup\Ecommerce\Tasks\EcommerceTaskReviewSearches
  EcommerceTaskCleanupProducts: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCleanupProducts
  EcommerceTaskReviewReports: Sunnysideup\Ecommerce\Tasks\EcommerceTaskReviewReports
  EcommerceTaskSetDefaultProductGroupValues: Sunnysideup\Ecommerce\Tasks\EcommerceTaskSetDefaultProductGroupValues
  EcommerceTaskCartManipulationCurrent: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCartManipulationCurrent
  EcommerceTaskFixBrokenOrderSubmissionData: Sunnysideup\Ecommerce\Tasks\EcommerceTaskFixBrokenOrderSubmissionData
  EcommerceTaskDefaultRecords: Sunnysideup\Ecommerce\Tasks\EcommerceTaskDefaultRecords
  EcommerceTaskCleanupProductFullSiteTreeSorting: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCleanupProductFullSiteTreeSorting
  EcommerceTaskCountryAndRegion: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCountryAndRegion
  EcommerceTaskDeleteProducts: Sunnysideup\Ecommerce\Tasks\EcommerceTaskDeleteProducts
  EcommerceTaskCountryAndRegionAllowAllCountries: Sunnysideup\Ecommerce\Tasks\EcommerceTaskCountryAndRegionAllowAllCountries
  EcommerceTaskDebugCart: Sunnysideup\Ecommerce\Tasks\EcommerceTaskDebugCart
  EcommerceTaskOrderItemsPerCustomer: Sunnysideup\Ecommerce\Tasks\EcommerceTaskOrderItemsPerCustomer
  OrderFiltersMustHaveAtLeastOnePayment: Sunnysideup\Ecommerce\Search\Filters\OrderFiltersMustHaveAtLeastOnePayment
  OrderFiltersAroundDateFilter: Sunnysideup\Ecommerce\Search\Filters\OrderFiltersAroundDateFilter
  OrderFiltersMultiOptionsetStatusIDFilter: Sunnysideup\Ecommerce\Search\Filters\OrderFiltersMultiOptionsetStatusIDFilter
  OrderFiltersMemberAndAddress: Sunnysideup\Ecommerce\Search\Filters\OrderFiltersMemberAndAddress
  OrderFiltersHasBeenCancelled: Sunnysideup\Ecommerce\Search\Filters\OrderFiltersHasBeenCancelled
  OrderEmailRecordFiltersMultiOptionsetStatusIDFilter: Sunnysideup\Ecommerce\Search\Filters\OrderEmailRecordFiltersMultiOptionsetStatusIDFilter
  EcommercePaymentFiltersAroundDateFilter: Sunnysideup\Ecommerce\Search\Filters\EcommercePaymentFiltersAroundDateFilter
  EcommerceSideReportEcommercePages: Sunnysideup\Ecommerce\Reports\EcommerceSideReportEcommercePages
  EcommerceSideReportAllProducts: Sunnysideup\Ecommerce\Reports\EcommerceSideReportAllProducts
  EcommerceSideReportNoPriceProducts: Sunnysideup\Ecommerce\Reports\EcommerceSideReportNoPriceProducts
  EcommerceSideReportFeaturedProducts: Sunnysideup\Ecommerce\Reports\EcommerceSideReportFeaturedProducts
  EcommerceSideReportNoImageProducts: Sunnysideup\Ecommerce\Reports\EcommerceSideReportNoImageProducts
  EcommerceSideReportNotForSale: Sunnysideup\Ecommerce\Reports\EcommerceSideReportNotForSale
  EcommerceSideReportNoInternalIDProducts: Sunnysideup\Ecommerce\Reports\EcommerceSideReportNoInternalIDProducts
