<?php

include 'lang/es_MX.php';
include 'lang/id_ID.php';
include 'lang/ar_SA.php';
include 'lang/nb_NO.php';
include 'lang/nl_NL.php';
include 'lang/fr_FR.php';
include 'lang/pl_PL.php';
include 'lang/tr_TR.php';
include 'lang/fi_FI.php';
include 'lang/hr_HR.php';
include 'lang/de_DE.php';
include 'lang/it_IT.php';
include 'lang/ru_RU.php';
include 'lang/en_GB.php';
include 'lang/et_EE.php';
include 'lang/ms_MY.php';
include 'lang/bg_BG.php';
include 'lang/da_DK.php';
include 'lang/zh_TW.php';
include 'lang/pt_PT.php';
include 'lang/en_US.php';
include 'lang/es_ES.php';
include '_config.php';
include 'tests/EcommerceTest.php';
include 'tmp.php';
include 'code/api/OrderConverter.php';
include 'code/api/EcommerceRestfulServer.php';
include 'code/api/EcommerceCountryVisitorCountryProvider.php';
include 'code/api/ShoppingCart.php';
include 'code/api/ProductCollection.php';
include 'code/api/Converters/OrderToArray.php';
include 'code/interfaces/EcommercePaymentSupportedMethodsProviderInterface.php';
include 'code/interfaces/OrderStepInterface.php';
include 'code/interfaces/EcommerceGEOipProvider.php';
include 'code/interfaces/EditableEcommerceObject.php';
include 'code/interfaces/BuyableModel.php';
include 'code/reports/EcommerceSideReportEcommercePages.php';
include 'code/reports/EcommerceSideReportAllProducts.php';
include 'code/reports/EcommerceSideReportNoPriceProducts.php';
include 'code/reports/EcommerceSideReportFeaturedProducts.php';
include 'code/reports/EcommerceSideReportNoImageProducts.php';
include 'code/reports/EcommerceSideReportNotForSale.php';
include 'code/reports/EcommerceSideReportNoInternalIDProducts.php';
include 'code/tasks/EcommerceTaskCountryAndRegionDisallowAllCountries.php';
include 'code/tasks/EcommerceTaskAPIandMore.php';
include 'code/tasks/EcommerceTaskTemplateTest.php';
include 'code/tasks/EcommerceTaskSetOrderIDStartingNumber.php';
include 'code/tasks/EcommerceTaskAddDefaultProducts.php';
include 'code/tasks/EcommerceTaskCreateMemberGroups.php';
include 'code/tasks/EcommerceTaskBuildingModel.php';
include 'code/tasks/EcommerceTaskLinkProductsWithImages.php';
include 'code/tasks/EcommerceTaskOrdersWithoutOrderStep.php';
include 'code/tasks/EcommerceTaskCartManipulationDebug.php';
include 'code/tasks/EcommerceTaskProductVariationsFixes.php';
include 'code/tasks/EcommerceTaskArchiveAllOrdersWithItems.php';
include 'code/tasks/EcommerceTaskAddCustomersToCustomerGroups.php';
include 'code/tasks/EcommerceTaskBuildingExtending.php';
include 'code/tasks/EcommerceTaskProductImageReset.php';
include 'code/tasks/EcommerceTaskArchiveAllSubmittedOrders.php';
include 'code/tasks/EcommerceTaskCartCleanup.php';
include 'code/tasks/EcommerceTaskTryToFinaliseOrders.php';
include 'code/tasks/EcommerceTaskCheckConfiguration.php';
include 'code/tasks/EcommerceTaskDeleteAllOrders.php';
include 'code/tasks/EcommerceTaskProcessOrderQueue.php';
include 'code/tasks/EcommerceTaskLinkOrderAddressesAtBothEnds.php';
include 'code/tasks/EcommerceTaskReviewSearches.php';
include 'code/tasks/EcommerceTaskCleanupProducts.php';
include 'code/tasks/EcommerceTaskReviewReports.php';
include 'code/tasks/EcommerceTaskSetDefaultProductGroupValues.php';
include 'code/tasks/EcommerceTaskFixBrokenOrderSubmissionData.php';
include 'code/tasks/EcommerceTaskDefaultRecords.php';
include 'code/tasks/EcommerceTaskCleanupProductFullSiteTreeSorting.php';
include 'code/tasks/EcommerceTaskCountryAndRegion.php';
include 'code/tasks/EcommerceTaskDeleteProducts.php';
include 'code/tasks/EcommerceTaskCountryAndRegionAllowAllCountries.php';
include 'code/tasks/EcommerceTaskDebugCart.php';
include 'code/tasks/EcommerceTaskCartManipulation.php';
include 'code/tasks/EcommerceTaskOrderItemsPerCustomer.php';
include 'code/forms/validation/OrderFormAddressValidator.php';
include 'code/forms/validation/ShopAccountFormValidator.php';
include 'code/forms/validation/OrderFormCancelValidator.php';
include 'code/forms/validation/OrderFormValidator.php';
include 'code/forms/validation/OrderStatusLogFormValidator.php';
include 'code/forms/validation/EcommercePaymentFormSetupAndValidation.php';
include 'code/forms/validation/OrderFormPaymentValidator.php';
include 'code/forms/validation/ProductSearchFormValidator.php';
include 'code/forms/validation/ShopAccountFormPasswordValidator.php';
include 'code/forms/validation/OrderModifierFormValidator.php';
include 'code/forms/validation/OrderFormFeedbackValidator.php';
include 'code/forms/gridfield/GridFieldAddNewButtonOriginalPage.php';
include 'code/forms/gridfield/GridFieldPrintInvoiceButton.php';
include 'code/forms/gridfield/GridFieldExportSalesButton.php';
include 'code/forms/gridfield/GridFieldEditButtonOriginalPage.php';
include 'code/forms/gridfield/GridFieldPrintAllPackingSlipsButton.php';
include 'code/forms/gridfield/GridFieldPrintAllInvoicesButton.php';
include 'code/forms/gridfield/configs/GridFieldBasicPageRelationConfig.php';
include 'code/forms/gridfield/configs/GridFieldEditOriginalPageConfigWithDelete.php';
include 'code/forms/gridfield/configs/GridFieldEditOriginalPageConfigWithAddExisting.php';
include 'code/forms/gridfield/configs/GridFieldConfigForOrderItems.php';
include 'code/forms/gridfield/configs/GridFieldBasicPageRelationConfigNoAddExisting.php';
include 'code/forms/gridfield/configs/GridFieldEditOriginalPageConfig.php';
include 'code/forms/gridfield/GridFieldPrintPackingSlipButton.php';
include 'code/forms/OrderFormAddress.php';
include 'code/forms/fields/OptionalTreeDropdownField.php';
include 'code/forms/fields/EcomQuantityField.php';
include 'code/forms/fields/EcommerceSearchHistoryFormField.php';
include 'code/forms/fields/OrderStepField.php';
include 'code/forms/fields/BuyableSelectField.php';
include 'code/forms/fields/SelectOrderAddressField.php';
include 'code/forms/fields/EcommerceClassNameOrTypeDropdownField.php';
include 'code/forms/fields/EcommerceCreditCardField.php';
include 'code/forms/fields/EcommerceCMSButtonField.php';
include 'code/forms/fields/ExpiryDateField.php';
include 'code/forms/fields/ProductProductImageUploadField.php';
include 'code/forms/OrderFormPayment.php';
include 'code/forms/OrderFormCancel.php';
include 'code/forms/ProductSearchFormShort.php';
include 'code/forms/OrderForm.php';
include 'code/forms/OrderFormFeedback.php';
include 'code/forms/ShopAccountForm.php';
include 'code/forms/OrderStatusLogForm.php';
include 'code/forms/OrderModifierForm.php';
include 'code/forms/ProductSearchForm.php';
include 'code/config/EcommerceConfigDefinitions.php';
include 'code/config/EcommerceConfig.php';
include 'code/config/EcommerceConfigAjaxDefinitions.php';
include 'code/config/EcommerceConfigAjax.php';
include 'code/dev/EcommerceCodeFilter.php';
include 'code/email/OrderInvoiceEmail.php';
include 'code/email/OrderErrorEmail.php';
include 'code/email/EcommerceDummyMailer.php';
include 'code/email/OrderStatusEmail.php';
include 'code/email/OrderReceiptEmail.php';
include 'code/email/OrderEmail.php';
include 'code/control/OrderModifierFormController.php';
include 'code/control/OrderStatusLogFormController.php';
include 'code/control/EcommerceResponse.php';
include 'code/control/EcommercePaymentController.php';
include 'code/control/BuyableSelectFieldDataList.php';
include 'code/control/EcommerceSiteTreeExtensionController.php';
include 'code/control/EcommerceTemplateTest.php';
include 'code/control/OrderStepController.php';
include 'code/control/ShoppingCartController.php';
include 'code/control/CartResponse.php';
include 'code/control/OrderEmailRecordReview.php';
include 'code/cms/SalesAdmin.php';
include 'code/cms/ProductsAndGroupsModelAdmin.php';
include 'code/cms/CMSPageAddControllerProducts.php';
include 'code/cms/ModelAdminEcommerceBaseClass.php';
include 'code/cms/dev/EcommerceDevelopmentAdminDecorator.php';
include 'code/cms/dev/EcommerceDatabaseAdmin.php';
include 'code/cms/dev/EcommerceDatabaseAdminDebugView.php';
include 'code/cms/SalesAdminExtras.php';
include 'code/cms/ProductConfigModelAdmin.php';
include 'code/cms/ProductBulkLoader.php';
include 'code/cms/StoreAdmin.php';
include 'code/search/filters/OrderFiltersMustHaveAtLeastOnePayment.php';
include 'code/search/filters/OrderFiltersAroundDateFilter.php';
include 'code/search/filters/OrderFiltersMultiOptionsetStatusIDFilter.php';
include 'code/search/filters/OrderFiltersMemberAndAddress.php';
include 'code/search/filters/OrderFiltersHasBeenCancelled.php';
include 'code/search/filters/OrderEmailRecordFiltersMultiOptionsetStatusIDFilter.php';
include 'code/search/filters/EcommercePaymentFiltersAroundDateFilter.php';
include 'code/filesystem/ProductImage.php';
include 'code/model/ProductOrderItem.php';
include 'code/model/process/CheckoutPageStepDescription.php';
include 'code/model/process/OrderSteps/OrderStepCreated.php';
include 'code/model/process/OrderSteps/OrderStepSentReceipt.php';
include 'code/model/process/OrderSteps/OrderStepSendAdminNotification.php';
include 'code/model/process/OrderSteps/OrderStepSent.php';
include 'code/model/process/OrderSteps/OrderStepSubmitted.php';
include 'code/model/process/OrderSteps/OrderStepArchived.php';
include 'code/model/process/OrderSteps/OrderStepConfirmed.php';
include 'code/model/process/OrderSteps/OrderStepPaid.php';
include 'code/model/process/OrderSteps/OrderStepSentInvoice.php';
include 'code/model/process/OrderStep.php';
include 'code/model/process/OrderEmailRecord.php';
include 'code/model/process/OrderProcessQueue.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogCancel.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogDispatchElectronicOrder.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogDispatch.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogSubmitted.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogArchived.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogPaymentCheck.php';
include 'code/model/process/OrderStatusLogs/OrderStatusLogDispatchPhysicalOrder.php';
include 'code/model/process/OrderStatusLog.php';
include 'code/model/process/OrderFeedback.php';
include 'code/model/config/EcommerceDBConfig.php';
include 'code/model/OrderAttribute.php';
include 'code/model/search/SearchReplacement.php';
include 'code/model/search/SearchHistory.php';
include 'code/model/address/EcommerceRegionVisitorRegionProvider.php';
include 'code/model/address/EcommerceRegion.php';
include 'code/model/address/ShippingAddress.php';
include 'code/model/address/EcommerceCountry.php';
include 'code/model/address/OrderAddress.php';
include 'code/model/address/BillingAddress.php';
include 'code/model/OrderModifierDescriptor.php';
include 'code/model/OrderItem.php';
include 'code/model/OrderModifier.php';
include 'code/model/Order.php';
include 'code/model/money/EcommerceCurrency.php';
include 'code/model/money/EcommercePayment.php';
include 'code/model/money/payment_types/EcommercePaymentTest.php';
include 'code/model/money/payment_types/EcommercePaymentTestPending.php';
include 'code/model/money/payment_types/EcommercePaymentTestSuccess.php';
include 'code/model/money/payment_types/EcommercePaymentTestFailure.php';
include 'code/model/fieldtypes/BuyableFieldType.php';
include 'code/model/OrderAttributeGroup.php';
include 'code/model/extensions/EcommerceRole.php';
include 'code/model/extensions/EcommerceSiteTreeExtension.php';
include 'code/Pages/CheckoutPageController.php';
include 'code/Pages/ProductGroupController.php';
include 'code/Pages/AccountPageController.php';
include 'code/Pages/ProductController.php';
include 'code/Pages/OrderConfirmationPage.php';
include 'code/Pages/ProductGroupSearchPage.php';
include 'code/Pages/CartPageController.php';
include 'code/Pages/CheckoutPage.php';
include 'code/Pages/AccountPage.php';
include 'code/Pages/ProductGroupSearchPageController.php';
include 'code/Pages/Product.php';
include 'code/Pages/ProductGroup.php';
include 'code/Pages/CartPage.php';
include 'code/Pages/OrderConfirmationPageController.php';
include 'code/money/EcommerceMoney.php';
include 'code/money/EcommercePaymentSupportedMethodsProvider.php';
include 'code/money/ExchangeRateProviderDummy.php';
include 'code/money/ExchangeRateProvider.php';
include 'code/money/payment/payment_results/EcommercePaymentProcessing.php';
include 'code/money/payment/payment_results/EcommercePaymentSuccess.php';
include 'code/money/payment/payment_results/EcommercePaymentFailure.php';
include 'code/money/payment/EcommercePaymentResult.php';


spl_autoload_register('myAutoloader');

function myAutoloader()
{
}
// $array = [
//     './code/api/EcommerceCountry_VisitorCountryProvider.php',
//     './code/reports/EcommerceSideReportFeaturedProducts.php',
//     './code/reports/EcommerceSideReportEcommercePages.php',
//     './code/reports/EcommerceSideReportNoInternalIDProducts.php',
//     './code/reports/EcommerceSideReportNoPriceProducts.php',
//     './code/reports/EcommerceSideReportAllProducts.php',
//     './code/reports/EcommerceSideReportNotForSale.php',
//     './code/reports/EcommerceSideReportNoImageProducts.php',
//     './code/tasks/EcommerceTaskBuildingExtending.php',
//     './code/tasks/EcommerceTaskBuildingModel.php',
//     './code/forms/OrderForm_Payment.php',
//     './code/forms/OrderForm_Feedback.php',
//     './code/forms/validation/OrderForm_Feedback_Validator.php',
//     './code/forms/validation/OrderFormAddress_Validator.php',
//     './code/forms/validation/ProductSearchForm_Validator.php',
//     './code/forms/validation/ShopAccountForm_PasswordValidator.php',
//     './code/forms/validation/ShopAccountFormValidator.php',
//     './code/forms/validation/OrderModifierForm_Validator.php',
//     './code/forms/validation/OrderForm_Cancel_Validator.php',
//     './code/forms/validation/OrderStatusLogForm_Validator.php',
//     './code/forms/fields/ProductProductImageUploadField.php',
//     './code/forms/ProductSearchFormShort.php',
//     './code/forms/OrderForm_Cancel.php',
//     './code/email/Order_StatusEmail.php',
//     './code/email/Order_InvoiceEmail.php',
//     './code/email/Order_ErrorEmail.php',
//     './code/email/Order_Email.php',
//     './code/email/Ecommerce_Dummy_Mailer.php',
//     './code/email/Order_ReceiptEmail.php',
//     './code/control/OrderEmailRecord_Review.php',
//     './code/control/OrderModifierForm_Controller.php',
//     './code/control/OrderStatusLogForm_Controller.php',
//     './code/control/ShoppingCartController.php',
//     './code/cms/CMSPageAddController_Products.php',
//     './code/search/filters/OrderFiltersMemberAndAddress.php',
//     './code/search/filters/OrderFiltersMustHaveAtLeastOnePayment.php',
//     './code/search/filters/OrderFiltersAroundDateFilter.php',
//     './code/search/filters/OrderFiltersHasBeenCancelled.php',
//     './code/search/filters/OrderFiltersMultiOptionsetStatusIDFilter.php',
//     './code/filesystem/Product_Image.php',
//     './code/model/ProductOrderItem.php',
//     './code/model/process/OrderSteps/OrderStepSent.php',
//     './code/model/process/OrderSteps/OrderStepSubmitted.php',
//     './code/model/process/OrderSteps/OrderStepSendAdminNotification.php',
//     './code/model/process/OrderSteps/OrderStepArchived.php',
//     './code/model/process/OrderSteps/OrderStepConfirmed.php',
//     './code/model/process/OrderSteps/OrderStepPaid.php',
//     './code/model/process/OrderSteps/OrderStepSentReceipt.php',
//     './code/model/process/OrderSteps/OrderStepSentInvoice.php',
//     './code/model/process/OrderSteps/OrderStepCreated.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogDispatchElectronicOrder.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogArchived.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogSubmitted.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogCancel.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogPaymentCheck.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogDispatch.php',
//     './code/model/process/OrderStatusLogs/OrderStatusLogDispatchPhysicalOrder.php',
//     './code/model/process/CheckoutPageStepDescription.php',
//     './code/model/OrderAttributeGroup.php',
//     './code/model/OrderModifierDescriptor.php',
//     './code/model/money/payment_types/EcommercePaymentTest.php',
//     './code/model/money/payment_types/EcommercePaymentTestSuccess.php',
//     './code/model/money/payment_types/EcommercePaymentTestFailure.php',
//     './code/model/money/payment_types/EcommercePaymentTestPending.php',
//     './code/money/payment/payment_results/EcommercePaymentSuccess.php',
//     './code/money/payment/payment_results/EcommercePaymentFailure.php',
//     './code/money/payment/payment_results/EcommercePaymentProcessing.php',
//     './code/money/payment/EcommercePaymentResult.php',
//     './code/money/ExchangeRateProviderDummy.php',
// ];
//
// foreach($array as $item) {
//     $items = explode('/', $item);
//     $name = array_pop($items);
//     $name = str_replace('.php', '', $name);
//     $newName = str_replace('_', '', $name);
//     echo '\''. $name .'\': \''.$newName.'\''."\n";
// }
