<?php

$array = [
    './code/api/EcommerceCountry_VisitorCountryProvider.php',
    './code/reports/EcommerceSideReport_FeaturedProducts.php',
    './code/reports/EcommerceSideReport_EcommercePages.php',
    './code/reports/EcommerceSideReport_NoInternalIDProducts.php',
    './code/reports/EcommerceSideReport_NoPriceProducts.php',
    './code/reports/EcommerceSideReport_AllProducts.php',
    './code/reports/EcommerceSideReport_NotForSale.php',
    './code/reports/EcommerceSideReport_NoImageProducts.php',
    './code/tasks/EcommerceTaskBuilding_Extending.php',
    './code/tasks/EcommerceTaskBuilding_Model.php',
    './code/forms/OrderForm_Payment.php',
    './code/forms/OrderForm_Feedback.php',
    './code/forms/validation/OrderForm_Feedback_Validator.php',
    './code/forms/validation/OrderFormAddress_Validator.php',
    './code/forms/validation/ProductSearchForm_Validator.php',
    './code/forms/validation/ShopAccountForm_PasswordValidator.php',
    './code/forms/validation/ShopAccountForm_Validator.php',
    './code/forms/validation/OrderModifierForm_Validator.php',
    './code/forms/validation/OrderForm_Cancel_Validator.php',
    './code/forms/validation/OrderStatusLogForm_Validator.php',
    './code/forms/fields/Product_ProductImageUploadField.php',
    './code/forms/ProductSearchForm_Short.php',
    './code/forms/OrderForm_Cancel.php',
    './code/email/Order_StatusEmail.php',
    './code/email/Order_InvoiceEmail.php',
    './code/email/Order_ErrorEmail.php',
    './code/email/Order_Email.php',
    './code/email/Ecommerce_Dummy_Mailer.php',
    './code/email/Order_ReceiptEmail.php',
    './code/control/OrderEmailRecord_Review.php',
    './code/control/OrderModifierForm_Controller.php',
    './code/control/OrderStatusLogForm_Controller.php',
    './code/control/ShoppingCart_Controller.php',
    './code/cms/CMSPageAddController_Products.php',
    './code/search/filters/OrderFilters_MemberAndAddress.php',
    './code/search/filters/OrderFilters_MustHaveAtLeastOnePayment.php',
    './code/search/filters/OrderFilters_AroundDateFilter.php',
    './code/search/filters/OrderFilters_HasBeenCancelled.php',
    './code/search/filters/OrderFilters_MultiOptionsetStatusIDFilter.php',
    './code/filesystem/Product_Image.php',
    './code/model/Product_OrderItem.php',
    './code/model/process/OrderSteps/OrderStep_Sent.php',
    './code/model/process/OrderSteps/OrderStep_Submitted.php',
    './code/model/process/OrderSteps/OrderStep_SendAdminNotification.php',
    './code/model/process/OrderSteps/OrderStep_Archived.php',
    './code/model/process/OrderSteps/OrderStep_Confirmed.php',
    './code/model/process/OrderSteps/OrderStep_Paid.php',
    './code/model/process/OrderSteps/OrderStep_SentReceipt.php',
    './code/model/process/OrderSteps/OrderStep_SentInvoice.php',
    './code/model/process/OrderSteps/OrderStep_Created.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_DispatchElectronicOrder.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_Archived.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_Submitted.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_Cancel.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_PaymentCheck.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_Dispatch.php',
    './code/model/process/OrderStatusLogs/OrderStatusLog_DispatchPhysicalOrder.php',
    './code/model/process/CheckoutPage_StepDescription.php',
    './code/model/OrderAttribute_Group.php',
    './code/model/OrderModifier_Descriptor.php',
    './code/model/money/payment_types/EcommercePayment_Test.php',
    './code/model/money/payment_types/EcommercePayment_TestSuccess.php',
    './code/model/money/payment_types/EcommercePayment_TestFailure.php',
    './code/model/money/payment_types/EcommercePayment_TestPending.php',
    './code/money/payment/payment_results/EcommercePayment_Success.php',
    './code/money/payment/payment_results/EcommercePayment_Failure.php',
    './code/money/payment/payment_results/EcommercePayment_Processing.php',
    './code/money/payment/EcommercePayment_Result.php',
    './code/money/ExchangeRateProvider_Dummy.php',
];

foreach($array as $item) {
    $items = explode('/', $item);
    $name = array_pop($items);
    $name = str_replace('.php', '', $name);
    $newName = str_replace('_', '', $name);
}
